# Generated by Django 4.2 on 2025-04-04 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('credit', models.TextField(blank=True, null=True)),
                ('debit', models.TextField(blank=True, null=True)),
                ('running_balance', models.TextField(blank=True, null=True)),
                ('created_ts', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
