# Generated by Django 4.2 on 2025-04-04 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
